'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(require.resolve('../admin.html'),'utf8');
function section(a,b){return html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)));}
const code=section('function errStorageDetail(', 'function errSortRows(')+'\n'+section('function readErrorPages(', 'function renderErrors(');
const date='2026-09-01T12:00:00.000Z';
function fixture(count=1251,serverCap=500){
 const rows=Array.from({length:count},(_,i)=>({id:count-i,created_at:date,event_name:'sync_failed'})),calls=[],nodes={errDays:{value:'7'},errSummary:{},errGroups:{},errRecent:{}};
 const c=vm.createContext({Promise,Date,Math,Number,String,Array,Error,encodeURIComponent,ERR:null,ERR_LIMIT:5000,ERR_TICKET:0,ERR_BUSY:false,adminAuthEpoch:1,adminSessionLocked:false,$:id=>nodes[id],errDaysVal:()=>+nodes.errDays.value,renderErrors:()=>{c.renders++;},renders:0,
  adminRequest:async q=>{calls.push(q);const p=new URL('https://fixture.invalid/'+q).searchParams,match=(p.get('or')||'').match(/id\.lt\.(\d+)/),before=match?+match[1]:Infinity;return rows.filter(r=>r.id<before).slice(0,Math.min(serverCap,+p.get('limit')));}});
 vm.runInContext(code,c);return {c,calls,rows,nodes};
}
test('error pagination reads past the server row cap without losing same-time rows',async()=>{const h=fixture(1251,200),r=await h.c.readErrorPages(7,()=>true);assert.equal(r.rows.length,1251);assert.equal(new Set(r.rows.map(r=>r.id)).size,1251);assert.equal(r.capped,false);assert.equal(h.calls.length,8);assert.ok(h.calls.every(q=>q.includes('order=created_at.desc,id.desc')));const cutoffs=h.calls.map(q=>new URL('https://fixture.invalid/'+q).searchParams.getAll('created_at').join('|'));assert.equal(new Set(cutoffs).size,1);});
for(const [count,capped] of [[5000,false],[5001,true]])test('accurate cap indicator for '+count+' rows',async()=>{const h=fixture(count),r=await h.c.readErrorPages(30,()=>true);assert.equal(r.rows.length,5000);assert.equal(r.capped,capped);});
test('a failed later page never publishes a partial success',async()=>{const h=fixture(),actual=h.c.adminRequest;h.c.adminRequest=async q=>{if(h.calls.length)throw Error('temporary server error');return actual(q);};await h.c.loadErrors(true);assert.equal(h.c.ERR.rows.length,0);assert.match(h.c.ERR.err,/temporary server/);});
test('period change during a fetch replaces the old result',async()=>{const h=fixture(3);let finish;h.c.adminRequest=()=>new Promise(r=>{finish=r;});const old=h.c.loadErrors(true);h.nodes.errDays.value='30';h.c.adminRequest=async()=>[];await h.c.loadErrors(true);finish(h.rows);await old;assert.equal(h.c.ERR.days,30);assert.equal(h.c.ERR.rows.length,0);assert.equal(h.c.renders,1);});
test('account change prevents stale errors being restored to cleared admin memory',async()=>{const h=fixture();let finish;h.c.adminRequest=()=>new Promise(r=>{finish=r;});const p=h.c.loadErrors(true);h.c.adminAuthEpoch++;h.c.adminSessionLocked=true;finish(h.rows);await p;assert.equal(h.c.ERR,null);assert.equal(h.c.renders,0);});
for(const msg of ['legacy and IndexedDB values differ','auxiliary storage versions differ'])test('conflicting copies are never diagnosed as a full disk: '+msg,()=>{const c=fixture().c,h=c.errHuman('sync_storage','sync_failed','storage',msg),r=c.errResolution('sync_storage','sync_failed','storage',msg);assert.match(h.name,/충돌/);assert.match(r,/보존/);assert.doesNotMatch(r,/공간.*확보/);});
for(const code of ['sync_local_changed','sync_workspace_changed'])test(code+' is explained as a protection stop',()=>{const c=fixture().c;assert.match(c.errHuman(code,'sync_failed','','').cause,/보호 동작/);assert.doesNotMatch(c.errResolution(code,'sync_failed','',''),/인터넷|공간.*확보/);});
for(const code of ['sync_server_rejected','sync_confirm_missing','match_not_ready','sync_conflict'])test('known logged condition has a concrete explanation: '+code,()=>{const c=fixture().c;assert.doesNotMatch(c.errHuman(code,'sync_failed','','').cause,/분류를 추가|설명이 없는/);assert.doesNotMatch(c.errResolution(code,'sync_failed','',''),/재분류/);});
test('IDP shape failures use the event name when error_code contains counters',()=>{const c=fixture().c;assert.match(c.errHuman('n4of4:idp-private-merge-shape','idp_docs_missing','','').name,/성장 기록/);assert.match(c.errResolution('n4of4','idp_docs_missing','',''),/병합 기준/);});
