const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../studio/analysis.html'),'utf8');
function setup(){const records=new Map(),c=vm.createContext({JSON,KEY:'teams',localStorage:{getItem:k=>records.get(k)||null,setItem:(k,v)=>records.set(k,v)}});vm.runInContext(source.slice(source.indexOf('function readTeams(){'),source.indexOf('function id(){')),c);return {c,records};}
test('team updates preserve other teams and legacy metadata without sharing references',()=>{const {c}=setup();c.saveTeam({id:'a',name:'A',players:[{id:'p',name:'One'}],formations:{base:{name:'4-3-3'}}});c.saveTeam({id:'b',name:'B',players:[]});const draft=c.copyTeam(c.readTeams().find(t=>t.id==='a'));draft.players[0].name='Two';assert.equal(c.readTeams().find(t=>t.id==='a').players[0].name,'One');c.saveTeam(draft);assert.equal(c.readTeams().length,2);assert.equal(c.readTeams().find(t=>t.id==='a').formations.base.name,'4-3-3');});
test('unreadable existing library is not silently replaced',()=>{const {c,records}=setup();records.set('teams','broken');assert.throws(()=>c.saveTeam({id:'a'}));assert.equal(records.get('teams'),'broken');});
test('failed persistence propagates without modifying stored teams',()=>{const {c}=setup();c.saveTeam({id:'a',name:'Before'});c.localStorage.setItem=()=>{throw Error('quota')};assert.throws(()=>c.saveTeam({id:'a',name:'After'}),/quota/);assert.equal(c.readTeams()[0].name,'Before');});
test('registration page does not mutate historical analysis or expose publishing',()=>{assert.equal(source.includes('cs_analysis_workspaces_v1'),false);assert.equal(source.includes('ps_community'),false);assert.equal(source.includes('커뮤니티에 올리기'),false);});
test('kit and emblem survive the saved team round trip',()=>{const {c}=setup();const t={id:'kit',name:'Kit',players:[],kit:{main:'#aa2244',gkMain:'#22aa66',pattern:'v'},emblem:'data:image/png;base64,aGVsbG8='};c.saveTeam(t);assert.deepEqual(JSON.parse(JSON.stringify(c.readTeams()[0])),t);});
test('imported kit changes only the selected board team',()=>{const b=fs.readFileSync(require.resolve('../studio/board.html'),'utf8'),start=b.indexOf('if(t.kit){var mapping='),end=b.indexOf('state.players=state.players.filter',start);const c=vm.createContext({t:{kit:{main:'#aa2244',gkMain:'#22aa66',pattern:'v',gkPattern:'solid'}},side:'red',state:{teamColors:{blue:'#123456'}},KIT_PATS:['solid','v']});vm.runInContext(b.slice(start,end),c);assert.equal(c.state.teamColors.red,'#aa2244');assert.equal(c.state.teamColors.blue,'#123456');assert.equal(c.state.gkColors.red,'#22aa66');assert.equal(c.state.teamPattern.red,'v');});
