const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../studio/analysis.html'),'utf8');
const api=require('../studio/team-library.js');
function setup(){
 const records=new Map(),durable=new Map();const w={localStorage:{getItem:k=>records.has(k)?records.get(k):null,setItem:(k,v)=>records.set(k,v)},storage:{get:async k=>({value:durable.get(k)??null})},PSStorage:{sharedReady:async()=>true,sharedVerified:async(k,raw)=>{assert.equal(durable.get(k),raw);}},psSaveSharedAsync:async(k,raw)=>{w.localStorage.setItem(k,raw);durable.set(k,raw);return true;}};
 const library=api.create(w),c={localStorage:w.localStorage,readTeams:()=>api.parse(records.get(api.key)??null),copyTeam:x=>JSON.parse(JSON.stringify(x)),saveTeam:team=>{const current=api.parse(records.get(api.key)??null).find(t=>t.id===team.id);return library.save(team,JSON.stringify(current||null),library.owner());}};
 return {c,records,durable,w,library};
}
test('team updates preserve other teams and legacy metadata without sharing references',async()=>{const {c}=setup();await c.saveTeam({id:'a',name:'A',players:[{id:'p',name:'One'}],formations:{base:{name:'4-3-3'}}});await c.saveTeam({id:'b',name:'B',players:[]});const draft=c.copyTeam(c.readTeams().find(t=>t.id==='a'));draft.players[0].name='Two';assert.equal(c.readTeams().find(t=>t.id==='a').players[0].name,'One');await c.saveTeam(draft);assert.equal(c.readTeams().length,2);assert.equal(c.readTeams().find(t=>t.id==='a').formations.base.name,'4-3-3');});
test('unreadable existing library is not silently replaced',()=>{const {c,records}=setup();records.set(api.key,'broken');assert.throws(()=>c.saveTeam({id:'a'}));assert.equal(records.get(api.key),'broken');});
test('failed persistence propagates without modifying stored teams',async()=>{const {c}=setup();await c.saveTeam({id:'a',name:'Before'});c.localStorage.setItem=()=>{throw Error('quota')};await assert.rejects(c.saveTeam({id:'a',name:'After'}),/quota/);assert.equal(c.readTeams()[0].name,'Before');});
test('registration page does not mutate historical analysis or expose publishing',()=>{assert.equal(source.includes('cs_analysis_workspaces_v1'),false);assert.equal(source.includes('ps_community'),false);assert.equal(source.includes('커뮤니티에 올리기'),false);});
test('kit and emblem survive the saved team round trip',async()=>{const {c}=setup();const t={id:'kit',name:'Kit',players:[],kit:{main:'#aa2244',gkMain:'#22aa66',pattern:'v'},emblem:'data:image/png;base64,aGVsbG8='};await c.saveTeam(t);assert.deepEqual(JSON.parse(JSON.stringify(c.readTeams()[0])),t);});
test('imported kit changes only the selected board team',()=>{const b=fs.readFileSync(require.resolve('../studio/board.html'),'utf8'),start=b.indexOf('if(t.kit){var mapping='),end=b.indexOf('state.players=state.players.filter',start);const c=vm.createContext({t:{kit:{main:'#aa2244',gkMain:'#22aa66',pattern:'v',gkPattern:'solid'}},side:'red',state:{teamColors:{blue:'#123456'}},KIT_PATS:['solid','v']});vm.runInContext(b.slice(start,end),c);assert.equal(c.state.teamColors.red,'#aa2244');assert.equal(c.state.teamColors.blue,'#123456');assert.equal(c.state.gkColors.red,'#22aa66');assert.equal(c.state.teamPattern.red,'v');});
function parse(text){const c=vm.createContext({});vm.runInContext(source.slice(source.indexOf('function parseRoster('),source.indexOf('var pendingRoster=')),c);return JSON.parse(JSON.stringify(c.parseRoster(text)));}
test('bulk roster preserves multiword names and accepts spreadsheet headers and empty optional fields',()=>{assert.deepEqual(parse('등번호\t이름\t포지션\n7\tTest Player\tlw\n\t가상 선수\t').players,[{no:'7',name:'Test Player',pos:'LW'},{no:'',name:'가상 선수',pos:''}]);});
test('malformed roster lines are reported rather than silently imported',()=>{const r=parse('7,Good Name,LW\n8 Missing Separator\n9,,ST');assert.equal(r.errors.length,2);assert.match(r.errors[0],/^2행/);assert.equal(r.players.length,1);assert.ok(parse(Array(101).fill('1,Player,ST').join('\n')).errors.length);});
test('vault route accepts registration only from its frame and clears team navigation context',()=>{const app=fs.readFileSync(require.resolve('../studio/app.html'),'utf8');const start=app.indexOf("if(d.type==='vaultSection'){");const end=app.indexOf("if(d.source==='board'",start);const code='(function(e,d){'+app.slice(start,end)+'})';const board={},note={},analysis={},game={};const seen=[];const c=vm.createContext({location:{origin:'https://test'},fBoard:{contentWindow:board},fNote:{contentWindow:note},fAnalysis:{contentWindow:analysis},fGameModel:{contentWindow:game},currentTeamKey:'team',showApp:x=>seen.push(x)});const handler=vm.runInContext(code,c);for(const [section,appName] of [['files','design'],['notes','note'],['gamemodel','gamemodel']]){handler({origin:'https://test',source:analysis},{type:'vaultSection',section});assert.equal(seen.at(-1),appName);assert.equal(c.currentTeamKey,'');}handler({origin:'https://evil',source:analysis},{type:'vaultSection',section:'files'});handler({origin:'https://test',source:{}},{type:'vaultSection',section:'files'});assert.equal(seen.length,3);});

test('missing mirror restores saved teams from durable storage before edit',async()=>{const f=setup(),raw=JSON.stringify([{id:'a',name:'Durable'}]);f.durable.set(api.key,raw);assert.equal((await f.library.read(f.library.owner()))[0].name,'Durable');assert.equal(f.records.get(api.key),raw);});
test('late durable read cannot overwrite a new mirror',async()=>{const f=setup();f.w.storage.get=async()=>{f.records.set(api.key,'[{"id":"new"}]');return {value:'[{"id":"old"}]'};};assert.equal((await f.library.read(f.library.owner()))[0].id,'new');});
test('owner changes during load preserve the next owner mirror',async()=>{const f=setup(),seal=f.library.owner();f.w.storage.get=async()=>{f.records.set('ps_ws_switch_epoch_v1','changed');return {value:'[{"id":"old"}]'};};await assert.rejects(f.library.read(seal),/바뀌었습니다/);assert.equal(f.records.has(api.key),false);});
test('durable save failure stays retryable without losing other teams',async()=>{const f=setup();await f.c.saveTeam({id:'a',name:'Before'});const base=JSON.stringify(f.c.readTeams()[0]),seal=f.library.owner(),writer=f.w.psSaveSharedAsync;f.w.psSaveSharedAsync=async(k,raw)=>{f.records.set(k,raw);throw Error('disk');};await assert.rejects(f.library.save({id:'a',name:'After'},base,seal),/disk/);assert.equal(f.c.readTeams()[0].name,'After');f.w.psSaveSharedAsync=writer;await f.library.save({id:'a',name:'After again'},base,seal);assert.equal(JSON.parse(f.durable.get(api.key))[0].name,'After again');});
test('same-team remote edits block stale drafts while other-team edits survive',async()=>{const f=setup();await f.c.saveTeam({id:'a',name:'Before'});const base=JSON.stringify(f.c.readTeams()[0]),seal=f.library.owner();await f.c.saveTeam({id:'b',name:'Other'});await f.library.save({id:'a',name:'Mine'},base,seal);assert.equal(f.c.readTeams().length,2);await assert.rejects(f.library.save({id:'a',name:'Stale'},base,seal),/다른 화면/);});
test('owner changes during save never report success',async()=>{const f=setup(),seal=f.library.owner();f.w.psSaveSharedAsync=async()=>{f.records.set('ps_ws_switch_epoch_v1','changed');return true;};await assert.rejects(f.library.save({id:'a'},'null',seal),/바뀌었습니다/);});
test('silent mirror write failure is detected during recovery',async()=>{const f=setup();f.durable.set(api.key,'[{"id":"a"}]');f.w.localStorage.setItem=()=>{};await assert.rejects(f.library.read(f.library.owner()),/불러오지/);assert.equal(f.durable.get(api.key),'[{"id":"a"}]');});
test('vault labels stay Team registration in model and note headers',()=>{for(const f of ['gamemodel.html','note.html']){const html=fs.readFileSync(require.resolve('../studio/'+f),'utf8');const nav=html.slice(html.indexOf('<nav class="vault-section-seg'),html.indexOf('</nav>',html.indexOf('<nav class="vault-section-seg')));assert.match(nav,/>팀 등록<\/button>/);assert.doesNotMatch(nav,/>분석<\/button>/);}});
