const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../studio/app.html'),'utf8');
const code=source.slice(source.indexOf('    var bootFinished=false;'),source.indexOf('    var hints='));
function harness(){
 const body=new Set(['ps-booting']),classes=new Set(),timers=[],msg={textContent:''},retry={addEventListener(type,fn){this.click=fn;}},board={document:{readyState:'loading'},__boardReadySent:false};
 const c={window:null,fBoard:{contentWindow:board},loading:{classList:{add:x=>classes.add(x)},style:{}},document:{body:{classList:{remove:x=>body.delete(x)},getAttribute:()=> 'board'},getElementById:id=>id==='psBootMessage'?msg:id==='psBootRetry'?retry:null},localStorage:{getItem:()=>null},setTimeout(fn,ms){const t={fn,ms};timers.push(t);return t;},clearTimeout(t){if(t)t.canceled=true;},psAutoReloadWhenSafe(manual){c.manualOnly=manual;c.__psForceReload=m=>{c.manualReload=m;};}};
 c.window=c;vm.runInNewContext(code,c);return {c,board,body,classes,msg,retry,timers};
}
test('five second guard never exposes a partially parsed board',()=>{const h=harness();h.c.__psShellBootReady=true;h.c.__psBootGuard.fn();assert.equal(h.body.has('ps-booting'),true);assert.equal(h.c.__psBoardBootReady,false);assert.equal(h.classes.has('ps-boot-slow'),true);assert.match(h.msg.textContent,/보드를 준비/);});
test('loaded document still waits for restored board and final layout signal',()=>{const h=harness();h.board.document.readyState='complete';h.board.__boardRestoreDone=true;h.c.__psShellBootReady=true;h.c.__psRevealAfterTidy();assert.equal(h.body.has('ps-booting'),true);h.board.__boardReadySent=true;h.c.__psBootCheck.fn();assert.equal(h.body.has('ps-booting'),false);assert.equal(h.classes.has('ps-boot-done'),true);});
test('missing message can recover from actual readiness but still waits for shell',()=>{const h=harness();h.board.document.readyState='complete';h.board.__boardReadySent=true;h.c.__psRevealAfterTidy();assert.equal(h.body.has('ps-booting'),true);h.c.__psShellBootReady=true;h.c.__psFinishBoot();assert.equal(h.body.has('ps-booting'),false);assert.equal(h.c.__psBootCheck.canceled,true);});
test('force flag cannot bypass either readiness prerequisite',()=>{const h=harness();h.c.__psFinishBoot(true);assert.equal(h.body.has('ps-booting'),true);h.c.__psBoardBootReady=true;h.c.__psFinishBoot(true);assert.equal(h.body.has('ps-booting'),true);});
test('unavailable frame remains hidden and retries readiness without navigation',()=>{const h=harness();Object.defineProperty(h.c.fBoard,'contentWindow',{get(){throw Error('not ready');}});h.c.__psRevealAfterTidy();assert.equal(h.body.has('ps-booting'),true);assert.equal(h.c.__psBootCheck.ms,500);});
test('manual retry uses existing save checked reload without starting automatic reloads',()=>{const h=harness();h.retry.click();assert.equal(h.c.manualOnly,true);assert.equal(h.c.manualReload,true);assert.equal(h.c.__psBootRetryRequested,true);h.msg.textContent='저장 확인 지연';h.c.__psRevealAfterTidy();assert.equal(h.msg.textContent,'저장 확인 지연');});
