'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../studio/idp.html'),'utf8');
function fn(name){const start=source.indexOf('  function '+name+'(');assert.ok(start>=0,name);const e=source.indexOf('\n',start);if(source.slice(start,e).trimEnd().endsWith('}'))return source.slice(start,e);const tail=source.slice(start),next=/\n  (?:function|var)\s/.exec(tail);assert.ok(next,name+' boundary');return tail.slice(0,next.index);}
const clone=x=>JSON.parse(JSON.stringify(x));
function mergeHarness(){const c={Date,console,sqMatchObject:v=>!!v&&typeof v==='object'&&!Array.isArray(v),ymd:d=>d.toISOString().slice(0,10),sqStEntries:d=>clone(d.legacy),stItems:()=>clone(c.events)};vm.createContext(c);vm.runInContext(['storyItemKey','storyCurrentEvalSnapshot','sqStoryItems','sqStoryKind'].map(fn).join('\n'),c);return c;}
test('one source item replaces the two renderings, while equal text on different dates is retained',()=>{const c=mergeHarness(),d={legacy:[{k:'log',day:'2026-09-01',id:'log:2026-09-01',said:'same',ts:2},{k:'log',day:'2026-09-02',id:'log:2026-09-02',said:'same',ts:3},{k:'qa',id:'q1',said:'answer',ts:4}]};c.events=[{k:'memo',d:'2026-09-01',text:'same'},{k:'memo',d:'2026-09-02',text:'same'},{k:'qa',id:'q1',text:'answer'},{k:'react',id:'day:2026-09-01',ts:5,text:'reply',who:'coach'}];const original=clone(d),rows=c.sqStoryItems(d);assert.equal(rows.length,4);assert.equal(rows.filter(x=>x.record?.said==='same').length,2);assert.equal(rows.filter(x=>x.record?.id==='q1').length,1);assert.equal(rows[0].text,'reply');assert.deepEqual(d,original);});
test('old and status-only logs, current assessment, goal stages and closed goal history remain distinct',()=>{const c=mergeHarness(),d={legacy:[{k:'log',day:'2020-01-01',ts:1,meta:'body only'},{k:'ev',ts:2,chips:[['skill',2]]},{k:'sw',ts:2,rows:[['good','strength','same']]},{k:'goal',id:'goal:g1',ts:3,meta:'3/5',said:'goal'}]};c.events=[{k:'qgoal',closed:false,q:{start:'2026-01-01'},ts:3},{k:'qgoal',closed:true,q:{start:'2025-01-01'},ts:1},{k:'self',e:{d:'2025-01-01',o:2},ts:1}];const rows=c.sqStoryItems(d);assert.equal(rows.length,6);assert.equal(rows.filter(x=>x.k==='qgoal').length,1);assert.ok(rows.some(x=>x.record?.meta==='body only'));assert.ok(rows.some(x=>x.record?.meta==='3/5'));});
test('distinct match, question, reaction and talk IDs do not collapse identical sentences',()=>{const c=mergeHarness();c.events=[{k:'mself',id:'m1',who:'me',text:'same',ts:4},{k:'mself',id:'m2',who:'me',text:'same',ts:4},{k:'match',id:'m1',who:'coach',text:'same',ts:4},{k:'talk',id:'t1',who:'me',text:'same',ts:4},{k:'talk',id:'t1',who:'coach',text:'same',ts:4},{k:'react',id:'day:d1',who:'coach',text:'same',ts:4}];const rows=c.sqStoryItems({legacy:[]});assert.equal(rows.length,6);assert.equal(new Set(rows.map(x=>x.key)).size,6);});
function contextHarness(){const state={uid:'coach',unlocked:true};const storage=new Map([['ps_sync_session',JSON.stringify({uid:'coach'})],['ps_active_ws','team'],['ps_ws_list',JSON.stringify([{id:'team',kind:'team',role:'owner'}])],['cs_perms_v1',JSON.stringify({members:{a:{playerId:'p-a',role:'player'},b:{playerId:'p-b',role:'player'},coach:{role:'executive'}}})],['cs_idp_v1_a',JSON.stringify({v:1,log:{}})],['cs_idp_v1_b',JSON.stringify({v:1,log:{secret:'B'}})]]);const reads=[];const c={PREFIX:'cs_idp_v1_',_idpRecoveryAuthLocked:false,squadView:true,sqEvalSel:'p-a',Date,console,localStorage:{getItem:k=>{reads.push(k);return storage.get(k)||null;},setItem:()=>assert.fail('read-only context wrote')},parent:{PSSync:{session:()=>({uid:state.uid}),dataUnlocked:()=>state.unlocked}}};c.window=c;vm.createContext(c);vm.runInContext(['sess','myKey','teamWsObj','onTeam','myTeamRole','isCoach','idpSaveApi','idpSaveOwner','sqMatchObject','sqStoryContext','sqStoryTarget','storyCoachTarget'].map(fn).join('\n'),c);return {c,state,storage,reads};}
test('story target uses the exact linked UID and never reads another player document',()=>{const h=contextHarness();assert.equal(h.c.sqStoryContext({id:'p-a'}).uid,'a');assert.equal(h.c.sqStoryTarget('a'),true);assert.equal(h.c.sqStoryTarget('b'),false);assert.equal(h.reads.includes('cs_idp_v1_b'),false);});
for(const kind of ['ambiguous','locked','changed-owner','missing-document','invalid-document'])test('story refuses '+kind+' rather than treating it as empty or writable',()=>{const h=contextHarness();if(kind==='ambiguous'){const pm=JSON.parse(h.storage.get('cs_perms_v1'));pm.members.b.playerId='p-a';h.storage.set('cs_perms_v1',JSON.stringify(pm));}if(kind==='locked')h.state.unlocked=false;if(kind==='changed-owner')h.state.uid='someone-else';if(kind==='missing-document')h.storage.delete('cs_idp_v1_a');if(kind==='invalid-document')h.storage.set('cs_idp_v1_a','{"v":2}');const ctx=h.c.sqStoryContext({id:'p-a'});assert.notEqual(ctx.state,'ready');assert.equal(h.c.storyCoachTarget('cs_idp_v1_a'),false);if(kind==='ambiguous')assert.equal(h.reads.includes('cs_idp_v1_a'),false);});

test('current evaluation and its exact latest snapshot are combined without losing the snapshot summary',()=>{const c=mergeHarness(),last={d:'2026-09-09',o:3,c:{skill:3},v:{pass:3},s:'standard'},d={selfEval:{at:Date.parse('2026-09-09T12:00:00Z'),setId:'standard',levels:{pass:3},hist:[last]},legacy:[{k:'ev',ts:2,chips:[['pass',3]]}]};c.stItems=()=>[{k:'self',ts:1,e:last}];const rows=c.sqStoryItems(d);assert.equal(rows.length,1);assert.equal(rows[0].record.snapshot.o,3);assert.deepEqual(rows[0].record.chips,[['pass',3]]);d.selfEval.levels.pass=4;assert.equal(c.sqStoryItems(d).length,2);d.selfEval.levels.pass=3;d.selfEval.setId='different';assert.equal(c.sqStoryItems(d).length,2);});
