const test=require('node:test'),assert=require('node:assert/strict'),{artwork,pdfBytes,point}=require('../studio/match-board-tools.js');
test('portrait geometry rotates points without altering stored coordinates',()=>{const p={x:20,y:35};assert.deepEqual(point(p,true),{x:35,y:80});assert.deepEqual(p,{x:20,y:35});});
test('saved drawing text and invalid geometry cannot inject SVG',()=>{const safe=artwork([{type:'text',x:10,y:20,text:'<script>alert(1)</script>',color:'" onload="bad'}],false);assert.ok(!safe.includes('<script'));assert.ok(safe.includes('&lt;script&gt;'));assert.equal(artwork([{type:'ball',x:'0" onload="bad',y:20}],false),'');assert.ok(!artwork([{type:'pen',x:1,y:1,points:[{x:'" bad',y:2}]}],false).includes('bad'));});
test('PDF cross-reference offsets use bytes and image payload is preserved',()=>{for(const portrait of [false,true]){const jpeg=Uint8Array.from([255,216,0,254,255,217]);const bytes=Buffer.from(pdfBytes(jpeg,1200,800,portrait)),s=bytes.toString('latin1');const start=Number(s.match(/startxref\n(\d+)/)[1]);assert.equal(s.slice(start,start+4),'xref');const refs=s.slice(start).split('\n').slice(3,8);refs.forEach((r,i)=>assert.equal(s.slice(Number(r.slice(0,10)),Number(r.slice(0,10))+7),(i+1)+' 0 obj'));assert.ok(bytes.includes(Buffer.from(jpeg)));assert.ok(s.includes(portrait?'595.28 841.89':'841.89 595.28'));}});
function harness(){
 const {mount}=require('../studio/match-board-tools.js');const nodes=new Map(),events={};const node=()=>({disabled:false,style:{},dataset:{},classList:{add(){},toggle(){}},setAttribute(){}});const svg={...node(),querySelectorAll:()=>[],addEventListener:(n,f)=>events[n]=f,setPointerCapture(){}};const dock={querySelector:s=>{if(!nodes.has(s))nodes.set(s,node());return nodes.get(s);},querySelectorAll:()=>[]};let current={key:'team/page',board:{us:[{num:'1'}],opp:[]}},editable=true,saves=0,textDone;const previous=global.document;global.document={createElementNS:()=>svg};const ctl=mount({pitch:{appendChild(){}},dock,state:()=>({...current}),canEdit:()=>editable,portrait:()=>false,point:e=>({x:e.x,y:e.y}),save:()=>saves++,draw:()=>ctl.sync(),text:fn=>textDone=fn});global.document=previous;
 const click=(kind,value)=>dock.onclick({target:{closest:()=>({dataset:{[kind]:value}})}});const pointer=(type,x=20,y=30)=>events[type]({button:0,pointerId:1,x,y,target:{closest:()=>null},preventDefault(){},stopPropagation(){}});
 return {ctl,click,pointer,get state(){return current},set state(v){current=v},get saves(){return saves},set editable(v){editable=v},text(v){textDone(v)}};
}
test('drawing undo preserves separately edited player positions',()=>{const h=harness();h.click('tool','ball');h.pointer('pointerdown');h.state.board.us[0].x=77;h.click('act','undo');assert.deepEqual(h.state.board.drawings,[]);assert.equal(h.state.board.us[0].x,77);h.click('act','redo');assert.equal(h.state.board.drawings.length,1);});
test('a stale drawing gesture cannot overwrite a different page or remotely changed drawings',()=>{for(const change of [h=>h.state={key:'another/page',board:{us:[],opp:[]}},h=>h.state.board.drawings=[{type:'ball',x:50,y:50}]]){const h=harness();h.click('tool','arrow');h.pointer('pointerdown');h.pointer('pointermove',40,50);change(h);const expected=JSON.stringify(h.state.board);h.pointer('pointerup');assert.equal(JSON.stringify(h.state.board),expected);assert.equal(h.saves,0);}});
test('delayed text cannot save after permission revocation',()=>{const h=harness();h.click('tool','text');h.pointer('pointerdown');h.editable=false;h.text('do not save');assert.equal(h.saves,0);assert.equal(h.state.board.drawings,undefined);});
test('stale undo history is not applied to a different page before rerender',()=>{const h=harness();h.click('tool','ball');h.pointer('pointerdown');h.state={key:'another/page',board:{us:[],opp:[],drawings:[{type:'cone',x:1,y:1}]}};h.click('act','undo');assert.equal(h.state.board.drawings[0].type,'cone');assert.equal(h.saves,1);});
