'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {create,prefix}=require('../studio/roster-outbox.js');
function storage(){const map=new Map(),reads=[],writes=[];return {map,reads,writes,get length(){return map.size;},key(i){return [...map.keys()][i]??null;},getItem(k){reads.push(k);return map.has(k)?map.get(k):null;},setItem(k,v){writes.push(k);if(this.failSet)throw new Error('quota');map.set(k,String(v));},removeItem(k){if(this.failRemove)throw new Error('remove');map.delete(k);}};}
function fixture(){const ls=storage(),owner={uid:'coach:a',wid:'team:b'};let who=owner;return {ls,owner,setOwner(o){who=o;},box:create({storage:ls,owner:()=>who}),clone(){return create({storage:ls,owner:()=>who});}};}
const p=(id,name,more={})=>({id,name,type:'ours',...more});
function stage(box,players,base,changed,deleted=[]){return box.stage({players,basePlayers:base,changedIds:changed,deletedIds:deleted});}
function values(ls){return [...ls.map.entries()];}

test('reload retains the exact original and latest row without shared references',()=>{const f=fixture(),old=p('p1','원래',{notes:{text:'첫 메모\r\n둘째 줄'}}),next=p('p1','수정',{notes:{text:'새 메모'}});const r=stage(f.box,[next],[old],['p1']);old.notes.text='mutated';next.name='mutated';r.rows[0].player.name='mutated receipt';const saved=f.clone().read();assert.equal(saved.rows.length,1);assert.equal(saved.rows[0].base.name,'원래');assert.equal(saved.rows[0].base.notes.text,'첫 메모\r\n둘째 줄');assert.equal(saved.rows[0].player.name,'수정');assert.equal(f.clone().pending(),true);});
test('rapid same-player edits retain earliest baseline and latest complete player',()=>{const f=fixture();const a=p('p1','A'),b=p('p1','B'),c=p('p1','C');stage(f.box,[b],[a],['p1']);stage(f.clone(),[c],[b],['p1']);const read=f.box.read();assert.equal(read.rows.length,1);assert.deepEqual(read.rows[0].base,a);assert.deepEqual(read.rows[0].player,c);assert.equal(read.rows[0].sources.length,2);});
test('late ACK for the first edit cannot erase the second edit',()=>{const f=fixture(),a=p('p1','A'),b=p('p1','B'),c=p('p1','C');const first=stage(f.box,[b],[a],['p1']),second=stage(f.box,[c],[b],['p1']);assert.equal(f.box.ack(first),1);assert.equal(f.box.read().rows[0].player.name,'C');assert.equal(f.box.read().rows[0].base.name,'A');assert.equal(f.box.ack(second),1);assert.equal(f.box.pending(),false);assert.equal(f.ls.length,0,'payloads and completed ACK markers are reclaimed');assert.equal(f.box.ack(second),0);});
test('ACK for latest edit also retires captured predecessor versions',()=>{const f=fixture();stage(f.box,[p('p1','B')],[p('p1','A')],['p1']);const last=stage(f.box,[p('p1','C')],[p('p1','B')],['p1']);assert.equal(f.box.ack(last),1);assert.equal(f.box.pending(),false);assert.equal(f.ls.length,0);});
test('ACK of an old read receipt leaves later edits and other IDs untouched',()=>{const f=fixture();stage(f.box,[p('p1','A1'),p('p2','B1')],[p('p1','A0'),p('p2','B0')],['p1','p2']);const read=f.box.read();stage(f.clone(),[p('p1','A2'),p('p2','B1')],[p('p1','A1'),p('p2','B1')],['p1']);assert.equal(f.box.ack(read),2);assert.deepEqual(f.box.read().rows.map(r=>[r.id,r.player.name]),[['p1','A2']]);});
test('partial receipt ACK preserves another player in the same batch',()=>{const f=fixture();const both=stage(f.box,[p('p1','A1'),p('p2','B1')],[p('p1','A0'),p('p2','B0')],['p1','p2']);const one={...both,rows:[both.rows[0]]};assert.equal(f.box.ack(one),1);assert.deepEqual(f.box.read().rows.map(r=>r.id),['p2']);assert.ok(f.ls.length>0);assert.equal(f.box.ack(f.box.read()),1);assert.equal(f.ls.length,0);});
test('overlay changes only pending IDs, preserves candidates, and does not mutate input',()=>{const f=fixture(),old=[p('p1','A'),p('p2','B'),{id:'candidate',name:'C',type:'target'}];stage(f.box,[p('p1','A1'),p('p3','C3')],old,['p1','p3'],['p2']);const result=f.clone().overlay(old);assert.deepEqual(result.map(x=>[x.id,x.name]),[['p1','A1'],['candidate','C'],['p3','C3']]);assert.equal(old[0].name,'A');assert.equal(old.length,3);const read=f.box.read();assert.equal(read.rows.find(r=>r.id==='p3').base,null);assert.equal(read.rows.find(r=>r.id==='p2').player,null);});
test('add then delete retains absence as baseline and does not resurrect after ACK',()=>{const f=fixture();const add=stage(f.box,[p('new','N')],[],['new']);const del=stage(f.box,[],[p('new','N')],[],['new']);assert.equal(f.box.read().rows[0].base,null);assert.equal(f.box.read().rows[0].deleted,true);f.box.ack(add);assert.deepEqual(f.box.overlay([]),[]);f.box.ack(del);assert.equal(f.box.pending(),false);});
test('delete then restore uses the original baseline and newest full row',()=>{const f=fixture();stage(f.box,[],[p('p1','A')],[],['p1']);const restored=stage(f.box,[p('p1','Restored')],[],['p1']);assert.equal(restored.rows[0].base.name,'A');assert.equal(f.box.read().rows[0].deleted,false);assert.equal(f.box.overlay([])[0].name,'Restored');});
test('another account or team never reads private payloads from the prior namespace',()=>{const f=fixture();const receipt=stage(f.box,[p('p1','private')],[p('p1','old')],['p1']);const keys=receipt.keys.slice();f.setOwner({uid:'other',wid:'team:b'});f.ls.reads.length=0;assert.equal(f.box.pending(),false);assert.deepEqual(f.box.read().rows,[]);assert.deepEqual(f.box.overlay([p('x','other')]),[p('x','other')]);assert.ok(keys.every(k=>!f.ls.reads.includes(k)));assert.throws(()=>f.box.ack(receipt),/다른 계정/);f.setOwner(f.owner);assert.equal(f.box.read().rows[0].player.name,'private');});
test('encoded owner IDs cannot collide across namespace separators',()=>{const ls=storage();const a=create({storage:ls,owner:()=>({uid:'x:y',wid:'z'})}),b=create({storage:ls,owner:()=>({uid:'x',wid:'y:z'})});stage(a,[p('p1','private')],[],['p1']);assert.deepEqual(b.read().rows,[]);assert.ok([...ls.map.keys()][0].startsWith(prefix+'x%3Ay:z:'));});
test('guest reads and overlays use no storage, and staging requires an owner',()=>{const f=fixture();f.setOwner(null);f.ls.reads.length=0;assert.deepEqual(f.box.read(),{owner:null,key:null,keys:[],rows:[]});assert.equal(f.box.pending(),false);assert.deepEqual(f.box.overlay([p('p1','A')]),[p('p1','A')]);assert.throws(()=>stage(f.box,[p('p1','A')],[],['p1']),/계정과 팀/);assert.equal(f.ls.reads.length,0);});
test('malformed existing JSON blocks further staging without replacing any original',()=>{const f=fixture(),receipt=stage(f.box,[p('p1','A')],[],['p1']);f.ls.map.set(receipt.keys[0],'{broken');const before=values(f.ls);assert.throws(()=>f.box.read(),/원문/);assert.throws(()=>stage(f.box,[p('p2','B')],[],['p2']),/원문/);assert.deepEqual(values(f.ls),before);});
test('stored owner mismatch fails closed without exposing or overwriting rows',()=>{const f=fixture(),r=stage(f.box,[p('p1','A')],[],['p1']);const d=JSON.parse(f.ls.map.get(r.keys[0]));d.uid='another';f.ls.map.set(r.keys[0],JSON.stringify(d));const before=values(f.ls);assert.throws(()=>f.box.read(),/소유자/);assert.throws(()=>stage(f.box,[p('p2','B')],[],['p2']),/소유자/);assert.deepEqual(values(f.ls),before);});
test('invalid changed/deleted IDs and unserializable input never create a batch',()=>{const f=fixture();for(const input of [{players:[p('p1','A')],basePlayers:[],changedIds:['missing'],deletedIds:[]},{players:[p('p1','A')],basePlayers:[],changedIds:['p1','p1'],deletedIds:[]},{players:[p('p1','A')],basePlayers:[],changedIds:[],deletedIds:['p1']},{players:[p('p1','A',{x:undefined})],basePlayers:[],changedIds:['p1'],deletedIds:[]},{players:[p('p1','A'),p('p1','B')],basePlayers:[],changedIds:['p1'],deletedIds:[]}])assert.throws(()=>f.box.stage(input));assert.equal(f.ls.length,0);});
test('empty and unnamed drafts can be retained without fake live roster row requirements',()=>{const f=fixture();assert.deepEqual(stage(f.box,[],[],[]).rows,[]);assert.equal(f.ls.length,0);stage(f.box,[p('p1','')],[],['p1']);assert.equal(f.box.read().rows[0].player.name,'');});
test('quota failure staging a later edit keeps every prior original',()=>{const f=fixture();stage(f.box,[p('p1','A1')],[p('p1','A0')],['p1']);const before=values(f.ls);f.ls.failSet=true;assert.throws(()=>stage(f.box,[p('p1','A2')],[p('p1','A1')],['p1']),/quota/);assert.deepEqual(values(f.ls),before);assert.equal(f.box.read().rows[0].player.name,'A1');});
test('ACK quota failure keeps the pending draft and does not report success',()=>{const f=fixture(),r=stage(f.box,[p('p1','A1')],[p('p1','A0')],['p1']);const before=values(f.ls);f.ls.failSet=true;assert.throws(()=>f.box.ack(r),/quota/);assert.deepEqual(values(f.ls),before);assert.equal(f.box.pending(),true);});
test('ACK checks exact captured row content before retiring its token',()=>{const f=fixture(),r=stage(f.box,[p('p1','A1')],[p('p1','A0')],['p1']);const doc=JSON.parse(f.ls.map.get(r.keys[0]));doc.rows[0].player.name='changed without this receipt';f.ls.map.set(r.keys[0],JSON.stringify(doc));assert.equal(f.box.ack(r),0);assert.equal(f.box.read().rows[0].player.name,'changed without this receipt');});
test('cleanup failure after durable ACK does not resurrect completed edits',()=>{const f=fixture(),r=stage(f.box,[p('p1','A1')],[p('p1','A0')],['p1']);f.ls.failRemove=true;assert.equal(f.box.ack(r),1);assert.equal(f.clone().pending(),false);assert.ok(f.ls.length>=2);});
test('owner change during reading returns no old owner receipt',()=>{const f=fixture(),r=stage(f.box,[p('p1','private')],[],['p1']);const get=f.ls.getItem.bind(f.ls);let once=true;f.ls.getItem=function(k){const raw=get(k);if(once&&k===r.keys[0]){once=false;f.setOwner({uid:'new',wid:'new'});}return raw;};assert.throws(()=>f.box.read(),/계정이나 팀/);});
test('a later batch carries intermediate originals after earlier ACK cleanup and reload',()=>{const f=fixture(),a=p('p1','A'),b=p('p1','B',{notes:'saved intermediate'}),c=p('p1','C');const first=stage(f.box,[b],[a],['p1']);const second=stage(f.box,[c],[b],['p1']);assert.deepEqual(second.rows[0].history,[b]);f.box.ack(first);const resumed=f.clone().read();assert.deepEqual(resumed.rows[0].base,a);assert.deepEqual(resumed.rows[0].player,c);assert.deepEqual(resumed.rows[0].history,[b]);assert.equal(f.ls.map.has(first.keys[0]),false,'the proof survives even when its old batch is reclaimed');});
test('every same-ID intermediate is copied and deduplicated in later durable batches',()=>{const f=fixture(),a=p('p1','A'),b=p('p1','B'),c=p('p1','C'),d=p('p1','D');const r1=stage(f.box,[b],[a],['p1']);const r2=stage(f.box,[c],[b],['p1']);stage(f.box,[b],[c],['p1']);const last=stage(f.box,[d],[b],['p1']);b.name='external mutation';assert.deepEqual(last.rows[0].history,[p('p1','B'),p('p1','C')]);f.box.ack(r1);f.box.ack(r2);assert.deepEqual(f.clone().read().rows[0].history,[p('p1','B'),p('p1','C')]);});
test('legacy batches without history remain readable and become proof for the next edit',()=>{const f=fixture(),r=stage(f.box,[p('p1','B')],[p('p1','A')],['p1']);const doc=JSON.parse(f.ls.map.get(r.keys[0]));delete doc.rows[0].history;f.ls.map.set(r.keys[0],JSON.stringify(doc));assert.deepEqual(f.clone().read().rows[0].history,[]);const next=stage(f.clone(),[p('p1','C')],[p('p1','B')],['p1']);assert.deepEqual(next.rows[0].history,[p('p1','B')]);});
test('history cannot introduce a different player or a tombstone as an authorized preimage',()=>{for(const bad of [[p('other','private')],[{id:'p1',_del:1}],null]){const f=fixture(),r=stage(f.box,[p('p1','B')],[p('p1','A')],['p1']);const doc=JSON.parse(f.ls.map.get(r.keys[0]));doc.rows[0].history=bad;f.ls.map.set(r.keys[0],JSON.stringify(doc));const before=values(f.ls);assert.throws(()=>f.clone().read(),/변경 행/);assert.throws(()=>stage(f.box,[p('p1','C')],[p('p1','B')],['p1']),/변경 행/);assert.deepEqual(values(f.ls),before);}});
