const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync(require.resolve('../studio/process.html'),'utf8');
const code=src.slice(src.indexOf('var __sessionTeamPick=null;'),src.indexOf('/* 2.483'));
function setup(){const sheet={},scrim={classList:{add(){}}},data=new Map();let saves=0,blocked=false;
 const day={d:'월',board:{sched:'훈련'},groupKinds:{'A팀':'OFF','B팀':'훈련'},trainings:[{slot:'old',time:'17:00',grp:['B팀'],note:'원본'}]};
 const c={window:null,week:[day],__schedGrp:'',localStorage:{getItem:k=>data.get(k)||null},document:{getElementById:id=>id==='sheet'?sheet:scrim},schedEditBlocked:()=>blocked,schedBlockNotice(){},schedGroups:()=>['A팀','B팀','C팀'],schedDayGrp:()=>'',schedDefGrp:()=> 'A팀',wkbdEsc:x=>String(x),closeSheet(){},toast(){},wksGroupKind:(d,g)=>d.groupKinds?.[g]||'',wksCommonTime:()=> '17:00',sesDefaults:x=>x,dayBoard:d=>d.board,save(){saves++},syncViews(){},wksFill(di,key){c.opened=key;}};c.window=c;vm.runInNewContext(code,c);return {c,day,sheet,data,saves:()=>saves,block:()=>blocked=true};}
test('opening and toggling the picker do not create or save a session',()=>{const h=setup(),before=JSON.stringify(h.day);h.c.wksChooseSession(0);h.c.wksSessionTeamToggle(1);assert.equal(JSON.stringify(h.day),before);assert.equal(h.saves(),0);assert.match(h.sheet.innerHTML,/참여 팀/);});
test('confirm creates one multi-team session, preserves old sessions and unselected team state',()=>{const h=setup(),old=JSON.stringify(h.day.trainings[0]);h.day.groupKinds['C팀']='OFF';h.c.wksChooseSession(0);h.c.wksSessionTeamToggle(1);h.c.wksConfirmSession();h.c.wksConfirmSession();assert.equal(h.day.trainings.length,2);assert.deepEqual(Array.from(h.day.trainings[1].grp),['A팀','B팀']);assert.equal(h.day.trainings[1].time,'19:00');assert.equal(h.day.groupKinds['A팀'],'훈련');assert.equal(h.day.groupKinds['C팀'],'OFF');assert.equal(JSON.stringify(h.day.trainings[0]),old);assert.equal(h.saves(),1);assert.equal(h.c.opened,h.day.trainings[1].slot);});
test('current B filter is selected by default and all selects each available team',()=>{const h=setup();h.c.__schedGrp='B팀';h.c.wksChooseSession(0);assert.deepEqual(Array.from(h.c.__sessionTeamPick.groups),['B팀']);h.c.wksSessionTeamToggle(-1);h.c.wksConfirmSession();assert.deepEqual(Array.from(h.day.trainings[1].grp),['A팀','B팀','C팀']);});
test('no selection cannot create a session',()=>{const h=setup();h.c.wksChooseSession(0);h.c.wksSessionTeamToggle(0);h.c.wksConfirmSession();assert.match(h.sheet.innerHTML,/disabled/);assert.equal(h.saves(),0);});
for(const change of ['owner','day','permission'])test('confirmation after '+change+' change leaves data intact',()=>{const h=setup();h.c.wksChooseSession(0);if(change==='owner')h.data.set('ps_active_ws','other');if(change==='day')h.c.week=[{d:'화'}];if(change==='permission')h.block();h.c.wksConfirmSession();assert.equal(h.day.trainings.length,1);assert.equal(h.day.groupKinds['A팀'],'OFF');assert.equal(h.saves(),0);});
test('adding A training on global OFF preserves the global OFF and B settings',()=>{const h=setup();h.day.off=true;h.day.board.sched='OFF';h.c.wksChooseSession(0);h.c.wksConfirmSession();assert.equal(h.day.off,true);assert.equal(h.day.board.sched,'OFF');assert.equal(h.day.groupKinds['A팀'],'훈련');assert.equal(h.day.groupKinds['B팀'],'훈련');});
test('weekly UI offers the picker and does not expose a separate group training editor',()=>{assert.match(src,/onclick="wksChooseSession\('\+di\+'\)"/);assert.doesNotMatch(src,/>조별 훈련 \/ OFF</);assert.doesNotMatch(src,/>\.wks-add\{display:none!important\}/);});
