-- READ ONLY. 운영 데이터베이스의 «우리가 만든 구조»를 다시 만들 수 있는 DDL 텍스트 한 칸(ddl)으로 돌려준다.
-- 행 값(팀·선수 자료)·비밀값은 읽지 않는다. 카탈로그만 읽는다.
-- 담는 것: 우리 스키마(public + Supabase/시스템이 아닌 스키마)의 확장·enum·시퀀스·표·제약·함수·뷰·색인·
--          트리거(우리 함수를 부르는 auth 트리거 포함)·RLS·정책·표/함수 권한·realtime 발행 표.
--          pg_cron 작업은 cron 스키마가 없는 DB 에서 이 쿼리가 깨지지 않게 scripts/schema-baseline.mjs 가 따로 묻는다.
-- 안 담는 것(맨 끝 «안 담긴 것» 주석에 개수로 남는다): 데이터, auth/storage 설정, 도메인·복합 타입·집계 함수,
--          열 단위 권한, 타입 주석, 스키마 권한, 소유자. 갱신·복원 절차는 00000000_baseline.runbook.md.
with
ours as (
  select n.oid, n.nspname from pg_namespace n
  where n.nspname !~ '^pg_' and n.nspname <> 'information_schema'
    and n.nspname not in ('auth','storage','realtime','_realtime','extensions','graphql','graphql_public','pgbouncer',
      'pgsodium','pgsodium_masks','supabase_functions','supabase_migrations','vault','net','cron','_analytics','tiger','topology')
    and not exists (select 1 from pg_depend d where d.classid='pg_namespace'::regclass and d.objid=n.oid and d.deptype='e')
),
ext_member as (select d.classid, d.objid from pg_depend d where d.deptype='e'),
rels as (
  select c.oid, c.relname, c.relkind, c.relrowsecurity, c.relforcerowsecurity, c.relacl, c.relowner, c.reloptions, o.nspname
  from pg_class c join ours o on o.oid=c.relnamespace
  where c.relkind in ('r','p','v','m','S') and not c.relispartition
    and not exists (select 1 from ext_member e where e.classid='pg_class'::regclass and e.objid=c.oid)
),
fns as (
  select p.oid, p.proname, p.prokind, p.proacl, p.proowner, o.nspname,
    format('%I.%I(%s)', o.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) sig
  from pg_proc p join ours o on o.oid=p.pronamespace
  where not exists (select 1 from ext_member e where e.classid='pg_proc'::regclass and e.objid=p.oid)
),
grantees as (
  select 0::oid oid, 'public'::text nm
  union all select r.oid, quote_ident(r.rolname) from pg_roles r where r.rolname in ('anon','authenticated','service_role')
),
sec as (
  select 1 o, '-- 0. 함수 본문은 만들 때 검사하지 않는다(표·함수 순서와 무관하게 다시 만들 수 있게)' || E'\n' || 'set check_function_bodies = off;' t
  union all select 2, '-- 1. 스키마' || coalesce(E'\n' || (select string_agg(format('create schema if not exists %I;', nspname), E'\n' order by nspname) from ours where nspname<>'public'), '')
  union all select 3, '-- 2. 확장' || coalesce(E'\n' || (select string_agg(format('create extension if not exists %I with schema %I;', e.extname, n.nspname), E'\n' order by e.extname)
      from pg_extension e join pg_namespace n on n.oid=e.extnamespace where e.extname<>'plpgsql'), '')
  union all select 4, '-- 3. enum' || coalesce(E'\n' || (select string_agg(format('create type %I.%I as enum (%s);', o.nspname, t.typname,
        (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) from pg_enum e where e.enumtypid=t.oid)), E'\n' order by o.nspname, t.typname)
      from pg_type t join ours o on o.oid=t.typnamespace where t.typtype='e'
        and not exists (select 1 from ext_member e where e.classid='pg_type'::regclass and e.objid=t.oid)), '')
  union all select 5, '-- 4. 시퀀스(식별 열이 아닌 것)' || coalesce(E'\n' || (select string_agg(format('create sequence if not exists %I.%I;', r.nspname, r.relname), E'\n' order by r.nspname, r.relname)
      from rels r where r.relkind='S'
        and not exists (select 1 from pg_depend d where d.classid='pg_class'::regclass and d.objid=r.oid and d.deptype='i')), '')
  union all select 6, '-- 5. 표' || coalesce(E'\n' || (select string_agg(
        format('create table if not exists %I.%I (%s)%s;', r.nspname, r.relname,
          (select string_agg(
             format('%I %s', a.attname, format_type(a.atttypid, a.atttypmod))
             || case when a.attidentity='a' then ' generated always as identity'
                     when a.attidentity='d' then ' generated by default as identity'
                     when a.attgenerated='s' then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
                     when ad.adbin is not null then ' default ' || pg_get_expr(ad.adbin, ad.adrelid) else '' end
             || case when a.attnotnull then ' not null' else '' end, ', ' order by a.attnum)
           from pg_attribute a left join pg_attrdef ad on ad.adrelid=a.attrelid and ad.adnum=a.attnum
           where a.attrelid=r.oid and a.attnum>0 and not a.attisdropped),
          case when r.relkind='p' then ' partition by ' || pg_get_partkeydef(r.oid) else '' end),
        E'\n' order by r.nspname, r.relname) from rels r where r.relkind in ('r','p')), '')
  union all select 7, '-- 6. 제약(기본키·유일·검사 먼저, 외래키 나중)' || coalesce(E'\n' || (select string_agg(format('alter table %I.%I add constraint %I %s;', r.nspname, r.relname, c.conname, pg_get_constraintdef(c.oid)), E'\n'
        order by (c.contype='f'), r.nspname, r.relname, c.conname)
      from pg_constraint c join rels r on r.oid=c.conrelid where c.contype in ('p','u','c','x','f') and c.conislocal), '')
  union all select 8, '-- 7. 함수' || coalesce(E'\n' || (select string_agg(rtrim(pg_get_functiondef(f.oid), E'\n') || ';', E'\n\n' order by f.nspname, f.proname, f.sig)
      from fns f where f.prokind in ('f','p')), '')
  union all select 9, '-- 8. 뷰' || coalesce(E'\n' || (select string_agg(
        case when r.relkind='v' then format('create or replace view %I.%I%s as %s;', r.nspname, r.relname,
               case when r.reloptions is not null then ' with (' || array_to_string(r.reloptions, ', ') || ')' else '' end,
               rtrim(rtrim(pg_get_viewdef(r.oid), E'\n'), ';'))
             else format('create materialized view if not exists %I.%I as %s with no data;', r.nspname, r.relname, rtrim(rtrim(pg_get_viewdef(r.oid), E'\n'), ';')) end,
        E'\n\n' order by r.nspname, r.relname) from rels r where r.relkind in ('v','m')), '')
  union all select 10, '-- 9. 색인(제약이 만든 것 제외)' || coalesce(E'\n' || (select string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' order by r.nspname, r.relname, ic.relname)
      from pg_index i join rels r on r.oid=i.indrelid join pg_class ic on ic.oid=i.indexrelid
      where not exists (select 1 from pg_constraint c where c.conindid=i.indexrelid and c.contype in ('p','u','x'))), '')
  union all select 11, '-- 10. 트리거' || coalesce(E'\n' || (select string_agg(pg_get_triggerdef(t.oid) || ';', E'\n' order by tn.nspname, tc.relname, t.tgname)
      from pg_trigger t join pg_class tc on tc.oid=t.tgrelid join pg_namespace tn on tn.oid=tc.relnamespace
      join pg_proc tp on tp.oid=t.tgfoid
      where not t.tgisinternal
        and (tc.oid in (select oid from rels) or tp.pronamespace in (select oid from ours))), '')
  union all select 12, '-- 11. 행 단위 보안' || coalesce(E'\n' || (select string_agg(
        format('alter table %I.%I enable row level security;', r.nspname, r.relname)
        || case when r.relforcerowsecurity then E'\n' || format('alter table %I.%I force row level security;', r.nspname, r.relname) else '' end,
        E'\n' order by r.nspname, r.relname) from rels r where r.relkind in ('r','p') and r.relrowsecurity), '')
  union all select 13, '-- 12. 정책' || coalesce(E'\n' || (select string_agg(
        format('create policy %I on %I.%I as %s for %s to %s%s%s;', p.polname, r.nspname, r.relname,
          case when p.polpermissive then 'permissive' else 'restrictive' end,
          case p.polcmd when 'r' then 'select' when 'a' then 'insert' when 'w' then 'update' when 'd' then 'delete' else 'all' end,
          (select string_agg(case when x=0 then 'public' else quote_ident(rr.rolname) end, ', ' order by case when x=0 then 'public' else rr.rolname::text end)
             from unnest(p.polroles) x left join pg_roles rr on rr.oid=x),
          case when p.polqual is not null then ' using (' || pg_get_expr(p.polqual, p.polrelid) || ')' else '' end,
          case when p.polwithcheck is not null then ' with check (' || pg_get_expr(p.polwithcheck, p.polrelid) || ')' else '' end),
        E'\n' order by r.nspname, r.relname, p.polname)
      from pg_policy p join rels r on r.oid=p.polrelid), '')
  union all select 14, '-- 13. 표 권한(public·anon·authenticated·service_role 만, 소유자 제외)' || coalesce(E'\n' || (select string_agg(stmt, E'\n' order by k1, k2, k3) from (
        select r.nspname || '.' || r.relname k1, 0 k2, '' k3,
          format('revoke all on table %I.%I from %s;', r.nspname, r.relname, (select string_agg(nm, ', ' order by nm) from grantees)) stmt
        from rels r where r.relkind in ('r','p','v','m') and r.relacl is not null
        union all
        select r.nspname || '.' || r.relname, 1, g.nm, format('grant %s on table %I.%I to %s;',
          string_agg(a.privilege_type, ', ' order by a.privilege_type), r.nspname, r.relname, g.nm)
        from rels r cross join lateral aclexplode(r.relacl) a join grantees g on g.oid=a.grantee
        where r.relkind in ('r','p','v','m') and a.grantee<>r.relowner
        group by r.nspname, r.relname, g.nm
      ) z), '')
  union all select 15, '-- 14. 함수 실행 권한(기본값과 다른 함수만)' || coalesce(E'\n' || (select string_agg(stmt, E'\n' order by k1, k2, k3) from (
        select f.sig k1, 0 k2, '' k3, format('revoke all on function %s from %s;', f.sig, (select string_agg(nm, ', ' order by nm) from grantees)) stmt
        from fns f where f.proacl is not null
        union all
        select f.sig, 1, g.nm, format('grant execute on function %s to %s;', f.sig, g.nm)
        from fns f cross join lateral aclexplode(f.proacl) a join grantees g on g.oid=a.grantee
        where a.grantee<>f.proowner and a.privilege_type='EXECUTE'
      ) z), '')
  union all select 16, '-- 15. realtime 발행 표' || coalesce(E'\n' || (select string_agg(format('alter publication %I add table %I.%I;', p.pubname, pn.nspname, pc.relname), E'\n' order by p.pubname, pn.nspname, pc.relname)
      from pg_publication p join pg_publication_rel pr on pr.prpubid=p.oid join pg_class pc on pc.oid=pr.prrelid join pg_namespace pn on pn.oid=pc.relnamespace
      where pc.oid in (select oid from rels)), '')
  union all select 17, '-- 16. 주석(표·뷰·시퀀스·열·함수·제약·정책·트리거)' || coalesce(E'\n' || (select string_agg(stmt, E'\n' order by stmt) from (
        select format('comment on %s %I.%I is %L;', case r.relkind when 'v' then 'view' when 'm' then 'materialized view' when 'S' then 'sequence' else 'table' end,
          r.nspname, r.relname, d.description) stmt
        from pg_description d join rels r on r.oid=d.objoid where d.classoid='pg_class'::regclass and d.objsubid=0
        union all
        select format('comment on column %I.%I.%I is %L;', r.nspname, r.relname, a.attname, d.description)
        from pg_description d join rels r on r.oid=d.objoid join pg_attribute a on a.attrelid=r.oid and a.attnum=d.objsubid
        where d.classoid='pg_class'::regclass and d.objsubid>0
        union all
        select format('comment on %s %s is %L;', case f.prokind when 'p' then 'procedure' else 'function' end, f.sig, d.description)
        from pg_description d join fns f on f.oid=d.objoid where d.classoid='pg_proc'::regclass and f.prokind in ('f','p')
        union all
        select format('comment on constraint %I on %I.%I is %L;', c.conname, r.nspname, r.relname, d.description)
        from pg_description d join pg_constraint c on c.oid=d.objoid join rels r on r.oid=c.conrelid where d.classoid='pg_constraint'::regclass
        union all
        select format('comment on policy %I on %I.%I is %L;', pl.polname, r.nspname, r.relname, d.description)
        from pg_description d join pg_policy pl on pl.oid=d.objoid join rels r on r.oid=pl.polrelid where d.classoid='pg_policy'::regclass
        union all
        select format('comment on trigger %I on %I.%I is %L;', t.tgname, tn.nspname, tc.relname, d.description)
        from pg_description d join pg_trigger t on t.oid=d.objoid join pg_class tc on tc.oid=t.tgrelid join pg_namespace tn on tn.oid=tc.relnamespace
        where d.classoid='pg_trigger'::regclass and not t.tgisinternal
      ) z), '')
  union all select 18, '-- 17. 안 담긴 것(복원 뒤 손으로 확인)' || E'\n-- ' || concat_ws(' · ',
      'domain ' || (select count(*) from pg_type t join ours o on o.oid=t.typnamespace where t.typtype='d'),
      'composite ' || (select count(*) from pg_type t join ours o on o.oid=t.typnamespace join pg_class c on c.oid=t.typrelid where t.typtype='c' and c.relkind='c'),
      'aggregate/window ' || (select count(*) from fns where prokind in ('a','w')),
      'column-grant ' || (select count(*) from pg_attribute a join rels r on r.oid=a.attrelid where a.attacl is not null),
      'enum-comment ' || (select count(*) from pg_description d join pg_type t on t.oid=d.objoid join ours o on o.oid=t.typnamespace where d.classoid='pg_type'::regclass))
)
select string_agg(t, E'\n\n' order by o) as ddl from sec;
