-- Synthetic history schema and catalog-exact RPC source. LOCAL PGLITE ONLY.
CREATE TABLE public.ps_kv_history (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id text NOT NULL,
 k text NOT NULL,v text,cupd bigint,changed_by uuid,changed_at timestamptz DEFAULT now()
);
CREATE OR REPLACE FUNCTION public.ps_kv_history_get(p_wid uuid, p_id bigint)
 RETURNS TABLE(id bigint, k text, v text, cupd bigint, changed_by uuid, changed_at timestamp with time zone)
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
declare
  my_role text;
begin
  if not exists (select 1 from public.ps_workspaces w
                 where w.id = p_wid and w.owner_id = auth.uid()) then
    select m.role into my_role
    from public.ps_members m
    where m.workspace_id = p_wid and m.user_id = auth.uid();
    if coalesce(my_role,'') not in ('owner','executive','admin') then
      raise exception 'executives only';
    end if;
  end if;
  return query
  select h.id, h.k, h.v, h.cupd, h.changed_by, h.changed_at
  from public.ps_kv_history h
  where h.workspace_id = p_wid::text and h.id = p_id
    and h.k not like 'cs\_idp\_v1\_%' and h.k not like 'cs\_idp\_pub\_v1\_%';
end;
$function$;
CREATE OR REPLACE FUNCTION public.ps_kv_history_list(p_wid uuid,p_key text DEFAULT NULL::text,p_limit integer DEFAULT 60)
 RETURNS TABLE(id bigint,k text,vlen integer,cupd bigint,changed_by uuid,changed_at timestamp with time zone)
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
declare
  my_role text;
begin
  if not exists (select 1 from public.ps_workspaces w
                 where w.id = p_wid and w.owner_id = auth.uid()) then
    select m.role into my_role
    from public.ps_members m
    where m.workspace_id = p_wid and m.user_id = auth.uid();
    if coalesce(my_role,'') not in ('owner','executive','admin') then
      raise exception 'executives only';
    end if;
  end if;
  return query
  select h.id, h.k, coalesce(length(h.v),0)::integer, h.cupd, h.changed_by, h.changed_at
  from public.ps_kv_history h
  where h.workspace_id = p_wid::text
    and (p_key is null or h.k = p_key)
    -- IDP(개인 문서)는 일반 멤버 select 정책(kv_sel_nonidp)도 빼놓는 키다 — 기록 통로도 같게.
    and h.k not like 'cs\_idp\_v1\_%' and h.k not like 'cs\_idp\_pub\_v1\_%'
  order by h.changed_at desc
  limit greatest(1, least(coalesce(p_limit,60), 200));
end;
$function$;
GRANT EXECUTE ON FUNCTION public.ps_kv_history_get(uuid,bigint),public.ps_kv_history_list(uuid,text,integer) TO PUBLIC,anon,authenticated,service_role;
